Gadget.WWW/Models/ErrorViewModel.cs
namespace Gadget.WWW.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Gadget.WWW/Controllers/DetailsController.cs
using Gadget.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Gadget.WWW.Models;
using Gadget.WWW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Gadget.Data.Data;
namespace Gadget.WWW.Controllers
{
    public class DetailsController : Controller
    {
        private readonly GadgetIntranetContext _context;

        public DetailsController(GadgetIntranetContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Details(int id)
        {
            var item = await _context.Products
                .Where(p=>p.Id == id)
                .Include(p=>p.Category)
                .Include(p=>p.Producer)
                .Include(p=>p.ProductSpecification)!
                    .ThenInclude(ps => ps.Specification)
                .FirstAsync();

            return View(item);
        }
    }
}

Gadget.WWW/Controllers/HomeController.cs
using Gadget.WWW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Gadget.Data.Data;

namespace Gadget.WWW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GadgetIntranetContext _context;

        public HomeController(ILogger<HomeController> logger, GadgetIntranetContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {

          
            //viewBag bedzie w gornej czesci layoutu wyswietlic wszystkie rodzaje towarow
            //ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            if (id == null)
            {
                id = 1; // to beda domyslnie towary promowane
            }
            //do items ladujemy wszystkie towary o danym rodzaju
            var items = await _context.Products
                .Include(p=> p.Producer)
                .Include(p => p.ProductSpecification)!
                .ThenInclude(ps => ps.Specification)
                .ToListAsync();


            return View(items);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gadget.WWW/Controllers/PagesController.cs
using Gadget.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gadget.WWW.Controllers
{
    public class PagesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GadgetIntranetContext _context;

        public PagesController(ILogger<HomeController> logger, GadgetIntranetContext context)
        {
            _logger = logger;
            _context = context;
        }
        public async Task<IActionResult> Index(int? id)
        {
            ViewBag.ModelStrony = await _context.Page.OrderBy(s => s.Position).ToListAsync();

            if (id == null)
                id = 2; //koniecznie powinna byc srona o id = 1
            // w bazie danych szukam strony o danym id
            var item = await _context.Page.FindAsync(id);
            // i te strone przekazuje do widoku
            return View(item);
        }
    }
}

Gadget.WWW/Controllers/PhoneController.cs
using Gadget.Data.Data;
using Gadget.Data.Data.Shop;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gadget.WWW.Controllers
{
    public class PhoneController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GadgetIntranetContext _context;

        public PhoneController(ILogger<HomeController> logger, GadgetIntranetContext context)
        {
            _logger = logger;
            _context = context;
        }
        public async Task<IActionResult> Index(string searchString)
        {
            var items =  _context.Products
                .Include(p => p.Category)
                .Where(p => p.Category.Name == "Phone")
                .Include(p => p.Producer)
                .Include(p => p.ProductSpecification)!
                .ThenInclude(ps => ps.Specification);

            if (!string.IsNullOrEmpty(searchString))
            {
                var item = await items.Where(p => p.Name.Contains(searchString)).ToListAsync();
                return View(item);
            }
            else
            {
                var products = await items.ToListAsync();

                return View(products);
            }
            
        }
        public async Task<IActionResult> Tablet(string searchString)
        {
            var items = _context.Products
                .Include(p => p.Category)
                .Where(p => p.Category.Name == "Tablet")
                .Include(p => p.Producer)
                .Include(p => p.ProductSpecification)!
                .ThenInclude(ps => ps.Specification);

            if (!string.IsNullOrEmpty(searchString))
            {
                var item = await items.Where(p => p.Name.Contains(searchString)).ToListAsync();
                return View(item);
            }
            else
            {
                var products = await items.ToListAsync();

                return View(products);
            }

        }
        public async Task<IActionResult> Deal(string searchString)
        {
            var items = _context.Products
                .Include(p => p.Category)
                .Where(p=> p.IsPromoted == true)
                .Include(p => p.Producer)
                .Include(p => p.ProductSpecification)!
                .ThenInclude(ps => ps.Specification);


            if (!string.IsNullOrEmpty(searchString))
            {
                var item = await items.Where(p => p.Category.Name.Contains(searchString)).ToListAsync();
                return View(item);
            }
            else
            {
                var products = await items.ToListAsync();

                return View(products);
            }


        }

    }
}

Gadget.WWW/Views/Details/Details.cshtml
@model Gadget.Data.Data.Shop.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <div class="col-sm-10">
        <img src="@Model.PhotoUrl" alt="Product Image" style="max-width: 100%; max-height: 400px;" />
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhotoUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Availability)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Availability)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producer.Name)
        </dd>
    </dl>
</div>

<div>
    <h4>Specifications</h4>
    <hr />
    <dl class="row">
        @foreach (var spec in Model.ProductSpecification)
        {
            <dt class="col-sm-2">
                @Html.DisplayFor(modelItem => spec.Specification.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => spec.Value)
            </dd>
        }
    </dl>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-dark">Back</a>
</div>

Gadget.WWW/Views/Home/Index.cshtml
@model IEnumerable<Gadget.Data.Data.Shop.Product> 
@{
    ViewData["Title"] = "Sklep";
}

<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="2000">
            <img src="img/tablet2.jpg" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="img/iphone1.jpg" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="img/samsung.jpg" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="img/iphone2.jpg" class="d-block w-100 img-fluid" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="img/tablet1.jpg" class="d-block w-100 img-fluid" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card">
                <img src="@item.PhotoUrl" class="card-img-top" alt="@item.Name">
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">Cena: @item.Price</p>
                    <p class="card-text">Producer: @item.Producer.Name</p>
                    <p class="card-text">
                        Display:
                        @{
                            var displaySpec = item.ProductSpecification
                                .FirstOrDefault(ps => ps.Specification.Name == "Display");
                            if (displaySpec != null)
                            {
                                @displaySpec.Value
                            }
                            else
                            {
                                @: "N/A"
                            }
                        }
                    </p>


                    <div style="display: flex; justify-content: center; gap: 2rem;">
                        <a href="#" class="btn btn-outline-dark">BUY</a>
                        <a asp-controller="Details" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-dark">Details</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<br/>
<br/>

Gadget.WWW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gadget</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gadget.WWW.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Great+Vibes&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">GADGET <sup>®</sup></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @await Component.InvokeAsync("PagesComponent")
            </div>
        </nav>
    </header>
    <div class="fluid-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gadget - <a asp-area="" asp-controller="Pages" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>