Gadget.Intranet/Controllers/CategoriesController.cs
using Gadget.Data.Data;
using Gadget.Data.Data.Shop;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gadget.Intranet.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly GadgetIntranetContext _context;

        public CategoriesController(GadgetIntranetContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Categories == null)
            {
                return NotFound();
            }
            return View(Categories);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Categories Categories)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Categories);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Categories);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Categories = await _context.Categories.FindAsync(id);
            if (Categories == null)
            {
                return NotFound();
            }
            return View(Categories);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Categories Categories)
        {
            if (id != Categories.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Categories);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriesExists(Categories.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Categories);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Categories == null)
            {
                return NotFound();
            }

            return View(Categories);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Categories = await _context.Categories.FindAsync(id);
            if (Categories != null)
            {
                _context.Categories.Remove(Categories);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriesExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Gadget.Intranet/Controllers/ProducersController.cs
using Gadget.Data.Data;
using Gadget.Data.Data.Shop;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gadget.Intranet.Controllers
{
    public class ProducersController : Controller
    {
        private readonly GadgetIntranetContext _context;

        public ProducersController(GadgetIntranetContext context)
        {
            _context = context;
        }

        // GET: Producers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producerss.ToListAsync());
        }

        // GET: Producerss/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Producers = await _context.Producerss
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Producers == null)
            {
                return NotFound();
            }

            return View(Producers);
        }

        // GET: Producerss/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producerss/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Producers Producers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Producers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Producers);
        }

        // GET: Producerss/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Producers = await _context.Producerss.FindAsync(id);
            if (Producers == null)
            {
                return NotFound();
            }
            return View(Producers);
        }

        // POST: Producerss/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Producers Producerss)
        {
            if (id != Producerss.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Producerss);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProducersExists(Producerss.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Producerss);
        }

        // GET: Producerss/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Producers = await _context.Producerss
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Producers == null)
            {
                return NotFound();
            }

            return View(Producers);
        }

        // POST: Producerss/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Producers = await _context.Producerss.FindAsync(id);
            if (Producers != null)
            {
                _context.Producerss.Remove(Producers);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProducersExists(int id)
        {
            return _context.Producerss.Any(e => e.Id == id);
        }
    }
}

Gadget.Intranet/Controllers/ProductsController.cs
using Gadget.Data.Data;
using Gadget.Data.Data.Shop;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Gadget.Intranet.Controllers
{
    public class ProductsController : Controller
    {
        private readonly GadgetIntranetContext _context;

        public ProductsController(GadgetIntranetContext context)
        {
            _context = context;
        }

        // GET: Products
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Producer)
                .ToListAsync();
            return View(products);
        }

        // GET: Products/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Producer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["ProducersId"] = new SelectList(_context.Producerss, "Id", "Name");
            ViewData["Specifications"] = new SelectList(_context.Specifications, "Id", "Name");
            ViewBag.SpecificationsVB = await _context.Specifications.ToListAsync();
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Product product, int[] specifications, string[] specValues)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();

                if (specifications != null && specValues != null)
                {
                    for (int i = 0; i < specifications.Length; i++)
                    {
                        var specId = specifications[i];
                        var specValue = specValues[i];

                        var productSpecification = new ProductSpecification
                        {
                            ProductId = product.Id,
                            SpecificationId = specId,
                            Value = specValue
                        };
                        _context.Add(productSpecification);
                    }
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            ViewData["ProducersId"] = new SelectList(_context.Producerss, "Id", "Name", product.ProducerId);

            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            ViewData["ProducersId"] = new SelectList(_context.Producerss, "Id", "Name", product.ProducerId);
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            ViewData["ProducersId"] = new SelectList(_context.Producerss, "Id", "Name", product.ProducerId);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Producer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

Gadget.Intranet/Views/Shared/ProductLinks.cshtml
@{
    ViewData["Title"] = "ProductLinks";
}

<h1>ProductLinks</h1>

Gadget.Intranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Gadget.Intranet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Gadget.Intranet.styles.css" asp-append-version="true"/>
</head>
<body>
<header>    
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <div class="navbar-left">
                <span style="color: black; font-weight: bold;">GADGET <sup>®</sup></span>
            </div>
            <div class="navbar-center">
                <a href="mailto:contact@gadget.com" style="color: black; font-weight: bold;">contact@gadget.com</a>
            </div>
            <div class="navbar-right">
                <span style="color: black; font-weight: bold;">+48 333 444 555</span>
            </div>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="btn btn-primary my-2 my-sm-0 me-2" asp-controller="Home" asp-action="Index">GADGET <sup>®</sup></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    @if (User.Identity is {IsAuthenticated: true } && (User.IsInRole("admin") || User.IsInRole("moderator")))
                    {
                        <li class="nav-item">
                            <a class="btn btn-secondary my-2 my-sm-2 " asp-controller="Pages" asp-action="Index">Pages</a>
                        </li>
                    }
                    @if (User.Identity is {IsAuthenticated: true } && User.IsInRole("admin"))
                    {
                        <li class="btn my-2 my-sm-0 me-2">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Products</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item nav-link text-black" asp-controller="Products" asp-action="Index" >Products</a>
                                <a class="dropdown-item nav-link text-black" asp-controller="Categories" asp-action="Index" >Categories</a>
                                <a class="dropdown-item nav-link text-black" asp-controller="Producers" asp-action="Index" >Producers</a>
                                <a class="dropdown-item nav-link text-black" asp-controller="Specifications" asp-action="Index" >Specifications</a>
                                <a class="dropdown-item nav-link text-black" asp-controller="ProductSpecifications" asp-action="Index" >Product - Specifications</a>
                            </div>
                        </li>
                            <li class="btn my-2 my-sm-0 me-2">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Users</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link text-black" asp-controller="AspNetUsers" asp-action="Index" >Users</a>
                                    <a class="dropdown-item nav-link text-black" asp-controller="AspNetRoles" asp-action="Index" >Roles</a>
                                    <a class="dropdown-item nav-link text-black" asp-controller="AspNetUserRoles" asp-action="Index" >User-Roles</a>
                                </div>
                            </li>
                        
                    }
                
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()

    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Gadget.Intranet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>